[package]
name = "libpintos"
version = "0.1.0"
authors = ["Gustav Sörnäs <gustav@sornas.net>"]
edition = "2018"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies.libc]
version = "0.2"
default-features = false
features = ["extra_traits"]
